# Generated by Django 2.2 on 2019-06-18 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_starter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200)),
                ('temp', models.CharField(max_length=100)),
                ('starter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Starter')),
            ],
        ),
        migrations.CreateModel(
            name='Rise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200)),
                ('temp', models.CharField(max_length=100)),
                ('leaven', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Leaven')),
            ],
        ),
    ]
