# Generated by Django 2.2 on 2019-06-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_leaven_rise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaven',
            name='starter',
        ),
        migrations.RemoveField(
            model_name='rise',
            name='leaven',
        ),
        migrations.AlterField(
            model_name='leaven',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
