# Generated by Django 2.2 on 2019-06-18 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_auto_20190618_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaven',
            name='starter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Starter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaven',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rise',
            name='starter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Starter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rise',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaven',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
